[package]
name = "directory-tags"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cdt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
